import org.jenkinsci.plugins.pipeline.modeldefinition.Utils

pipeline {
    agent any
    
    environment {
        BROWSERSTACK_CREDENTIALS = credentials('com.browserstack.automate.ci.jenkins.BrowserStackCredentials')
        BROWSERSTACK_USERNAME = "${BROWSERSTACK_CREDENTIALS}"
    }
    
    stages {
        stage('Pull code from GitHub') {
            steps {
                dir('test') {
                    git branch: 'main',
                        url: 'https://github.com/sanketsmali03/bstack-demo-web-regression.git'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                withCredentials([usernamePassword(credentialsId: BROWSERSTACK_CREDENTIALS, usernameVariable: 'BROWSERSTACK_USERNAME', passwordVariable: 'BROWSERSTACK_ACCESS_KEY')]) {
                    sshagent(['samirans89_demo_jenkins']) {
                        dir('test') {
                            sh '''
                                #!/bin/bash -e
                                git checkout main
                                export PERCY_TOKEN=${PERCY_TOKEN}
                                source ~/.bashrc
                                nvm use 16
                                npm install
                                export BROWSERSTACK_CONFIG_FILE=src/test/resources/conf/capabilities/bstack-parallel-browsers-regression.yml
                                npx percy exec --verbose  --  mvn test -P bstack-parallel-browsers
                            '''
                        }
                    }
                }
            }
        }
        
        stage('Generate Report') {
            steps {
                script {
                    browserStackReportPublisher 'automate'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
        failure {
            script {
                echo "Pipeline Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}]"
            }
        }
    }
}
